# Generated by Django 5.0.4 on 2024-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_img', models.ImageField(upload_to='Exercise_images')),
                ('muscles_name', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=80)),
            ],
        ),
    ]
