# Generated by Django 5.0.4 on 2024-05-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['muscles_name']},
        ),
    ]
