# Generated by Django 5.0.4 on 2024-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseApis',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('muscles', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Exercise_img_apis')),
                ('exercise_name', models.CharField(max_length=60)),
                ('equipment_required', models.CharField(max_length=50)),
            ],
        ),
    ]
