# Generated by Django 5.0.4 on 2024-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
