# Generated by Django 5.0.4 on 2024-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='photo',
            field=models.ImageField(upload_to='hero_images'),
        ),
    ]
