# Generated by Django 5.0.4 on 2024-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_herobanner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebookings',
            name='plan',
            field=models.CharField(max_length=100),
        ),
    ]
