# Generated by Django 5.0.4 on 2024-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_onlinebookings_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('age', models.IntegerField(default=18)),
                ('plan', models.CharField(max_length=100)),
                ('date_of_admissions', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
