# Generated by Django 5.0.4 on 2024-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_totalmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmembers',
            name='date_of_admissions',
            field=models.DateField(),
        ),
    ]
