# Generated by Django 5.0.4 on 2024-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_totalmembers_date_of_admissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmembers',
            name='date_of_admissions',
            field=models.DateField(blank=True, null=True),
        ),
    ]
