# Generated by Django 5.0.4 on 2024-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_totalmember_delete_totalmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
